# Generated by Django 5.1.7 on 2025-11-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillset',
            name='email',
        ),
        migrations.RemoveField(
            model_name='skillset',
            name='full_name',
        ),
    ]
