# Generated by Django 5.1.7 on 2025-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertb',
            name='enhanced_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
