# Generated by Django 5.1.7 on 2025-10-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='sender_name',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='sender_phone',
        ),
        migrations.AddField(
            model_name='letter',
            name='align_contact',
            field=models.CharField(choices=[('start', 'start'), ('end', 'end')], default='start', max_length=5),
        ),
        migrations.AddField(
            model_name='letter',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
