# Generated by Django 5.1.7 on 2025-11-18 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experiences', '0002_alter_responsibility_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
