# Generated by Django 5.1.7 on 2025-11-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experiences', '0003_alter_workexperience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
