# Generated by Django 5.1.7 on 2025-11-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experiences', '0004_alter_workexperience_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
