# Generated by Django 5.1.7 on 2025-12-07 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('harusi', 'Harusi'), ('msiba', 'Msiba'), ('uzinduzi', 'Uzinduzi'), ('mgeni_rasmi', 'Mgeni Rasmi')], max_length=50)),
                ('event_title', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=255)),
                ('guest_of_honor', models.CharField(blank=True, max_length=255)),
                ('guest_title', models.CharField(blank=True, max_length=255)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('organization_representative', models.CharField(blank=True, max_length=255)),
                ('purpose_statement', models.TextField(blank=True)),
                ('background_info', models.TextField(blank=True)),
                ('main_message', models.TextField(blank=True)),
                ('bride_name', models.CharField(blank=True, max_length=255)),
                ('groom_name', models.CharField(blank=True, max_length=255)),
                ('wedding_theme', models.CharField(blank=True, max_length=255)),
                ('deceased_name', models.CharField(blank=True, max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=255)),
                ('tribute_summary', models.TextField(blank=True)),
                ('requests', models.TextField(blank=True)),
                ('closing_statement', models.TextField(blank=True)),
                ('presenter_name', models.CharField(blank=True, max_length=255)),
                ('presenter_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
