# Generated by Django 5.1.7 on 2025-12-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risala',
            name='program_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='risala',
            name='program_theme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='risala',
            name='project_beneficiaries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='risala',
            name='project_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='risala',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
