# Generated by Django 5.1.7 on 2025-10-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
