# Generated by Django 5.1.7 on 2025-11-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0002_personaldetail_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
