# Generated by Django 5.1.7 on 2025-11-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0003_alter_personaldetail_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
