# Generated by Django 5.1.7 on 2025-11-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0004_alter_personaldetail_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
