# Generated by Django 5.2.4 on 2025-09-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('deadline', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField()),
                ('source_site', models.CharField(max_length=100)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
